# Generated by Django 2.2.4 on 2019-08-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='cron_tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djcelery.CrontabSchedule'),
        ),
        migrations.AddField(
            model_name='series',
            name='interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djcelery.IntervalSchedule'),
        ),
        migrations.AddField(
            model_name='series',
            name='periodic_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djcelery.PeriodicTask'),
        ),
    ]
