# Generated by Django 2.2.4 on 2019-08-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_series_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='api_key',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
